export const ORDER_STATUS_OPEN = 'OPEN';
export const ORDER_STATUS_CANCELED = 'CANCELED';
export const ORDER_STATUS_FILLED = 'FILLED';
export const ORDER_STATUS_PARTIALLY_FILLED = 'PARTIALLY_FILLED';
export const ORDER_STATUS_PENDING = 'PENDING';
