export const ORDERS_CANCEL = 'CANCEL_ROUTE';

export const ORDERS_PLACE = 'ORDERS_PLACE_ORDER';

export const ORDERS_BUY = 'ORDERS_BUY';

export const ORDERS_SELL = 'ORDERS_SELL';

export const ORDERS_CANCELL_ALL = 'ORDERS_CANCELL_ALL';

export const ORDERS_BUY_MANY = 'ORDERS_BUY_MANY';

export const ORDERS_SELL_MANY = 'ORDERS_SELL_MANY';
