export const ORDERS_CANCEL = 'ORDERS_CANCEL';
export const ORDERS_CANCEL_RESPONSE = 'ORDERS_CANCEL_RESPONSE';

export const ORDERS_PLACE_ORDER = 'ORDERS_PLACE_ORDER';
export const ORDERS_PLACE_RESPONSE = 'ORDERS_PLACE_RESPONSE';

export const ORDERS_BUY = 'ORDERS_BUY';
export const ORDERS_BUY_RESPONSE = 'ORDERS_BUY_RESPONSE';

export const ORDERS_SELL = 'ORDERS_SELL';
export const ORDERS_SELL_RESPONSE = 'ORDERS_SELL_RESPONSE';

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_RESPONSE = 'GET_ORDER_RESPONSE';

export const GET_MY_FILLS = 'GET_MY_FILLS';
export const GET_MY_FILLS_RESPONSE = 'GET_MY_FILLS_RESPONSE';

export const ORDERS_CANCEL_ALL = 'ORDERS_CANCEL_ALL';
export const ORDERS_CANCEL_ALL_RESPONSE = 'ORDERS_CANCEL_ALL_RESPONSE';

export const ORDERS_BUY_MANY = 'ORDERS_BUY_MANY';
export const ORDERS_BUY_MANY_RESPONSE = 'ORDERS_BUY_MANY_RESPONSE';

export const ORDERS_SELL_MANY = 'ORDERS_SELL_MANY';
export const ORDERS_SELL_MANY_RESPONSE = 'ORDERS_SELL_MANY_RESPONSE';

export const STATE_INTERNAL_PRICE = 'STATE_INTERNAL_PRICE';

export const STATE_EXTERNAL_PRICE = 'STATE_EXTERNAL_PRICE';

export const ORDERS_STATUS_CHANGES = 'ORDERS_STATUS_CHANGES';

export const BALANCES_CHANGES = 'BALANCES_CHANGES';

export const STOP_OPS = 'STOP_OPS';

export const ORDERS_PLACE_MANY = 'ORDERS_PLACE_MANY';
export const ORDERS_PLACE_MANY_RESPONSE = 'ORDERS_PLACE_MANY_RESPONSE';

export const ORDERS_CANCEL_MANY = 'ORDERS_CANCEL_MANY';
export const ORDERS_CANCEL_MANY_RESPONSE = 'ORDERS_CANCEL_MANY_RESPONSE';
